# 1、训练相关参数
lr0: 0.00334              # 初始学习率(SGD=1E-2, Adam=1E-3)
lrf: 0.15135              # 最终学习率, 以one_cycle形式或者线性从lr0衰减至lr0 * lrf
momentum: 0.74832         # SGD momentum/Adam beta1
weight_decay: 0.00025     # optimizer权重衰减系数 5e-4
warmup_epochs: 3.3835     # 前3个epoch进行warmup
warmup_momentum: 0.59462  # warmup初始化动量
warmup_bias_lr: 0.18657   # warmup初始bias学习率
# 2、损失函数相关参数
box: 0.02                 # box iou损失系数
cls: 0.21638              # cls分类损失系数
cls_pw: 0.5               # cls BCELoss正样本权重
obj: 0.51728              # obj loss gain (scale with pixels)
obj_pw: 0.67198           # obj BCELoss正样本权重
fl_gamma: 0.0             # focal loss gamma (efficientDet default gamma=1.5)
# 3、其他几个参数
iou_t: 0.2                # 训练时IoU阈值
anchor_t: 3.3744          #  anchor的长宽比阈值（长:宽 = 4:1） 用于k-means中计算 bpr和aat
# anchors: 3.412            # 每个输出层的anchors数量 (0 to ignore)
# 4、数据增强相关参数
hsv_h: 0.01041            # hsv增强系数 色调
hsv_s: 0.54703            # hsv增强系数 饱和度
hsv_v: 0.27739            # hsv增强系数 亮度
degrees: 0.0              # random_perspective增强系数 旋转角度  (+/- deg)
translate: 0.04591        # random_perspective增强系数 平移     (+/- fraction)
scale: 0.75544            # random_perspective增强系数 图像缩放  (+/- gain)
shear: 0.0                # random_perspective增强系数 图像剪切  (+/- deg)
perspective: 0.0          # random_perspective增强系数 透明度    (+/- fraction), range 0-0.001
flipud: 0.0               # 上下翻转数据增强(probability)
fliplr: 0.5               # 左右翻转数据增强(probability)
mosaic: 0.85834           # mosaic数据增强(probability)
mixup: 0.04266            # mixup数据增强(probability)
copy_paste: 0.0           # cutout数据增强(probability)
